/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";
import type { DateTime } from "luxon";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface AppSettings {
  key: string;
  updatedAt: Generated<DateTime>;
  value: Json;
}

export interface IcloudAccounts {
  accountName: string;
  addedAt: Generated<DateTime>;
  archivePrefix: string | null;
  id: Generated<string>;
  photosLayout: string | null;
  photosNaming: string | null;
  relocationError: string | null;
  relocationFrom: string | null;
  session: Buffer | null;
  sessionUpdatedAt: DateTime | null;
}

export interface IcloudPhotos {
  accountId: string;
  addedDate: bigint | null;
  assetDate: bigint | null;
  backedUpAt: DateTime | null;
  backupChecksum: string | null;
  backupKey: string | null;
  backupSize: bigint | null;
  filename: string | null;
  isDeleted: Generated<boolean>;
  isFavorite: Generated<boolean>;
  isHidden: Generated<boolean>;
  masterRecordName: string | null;
  recordName: string;
  resources: Generated<Json>;
  syncedAt: Generated<DateTime>;
}

export interface SchemaMigrations {
  version: string;
}

export interface DB {
  appSettings: AppSettings;
  icloudAccounts: IcloudAccounts;
  icloudPhotos: IcloudPhotos;
  schemaMigrations: SchemaMigrations;
}
